name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
        
    - name: Build application
      run: npm run build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-mac
        path: ./dist/*.zip