name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Clean install
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install
        
    - name: Verify NW.js
      run: |
        echo "NW.js versions available:"
        npm view nw versions --json
        echo "Installed version:"
        npm ls nw
        
    - name: Build with direct download
      run: |
        npx nwbuild \
          --nwVersion=0.77.0 \
          --flavor=sdk \
          --platform=osx64 \
          --downloadUrl=https://dl.nwjs.io \
          --cacheDir=./nw-cache \
          -o ./dist \
          .
          
    - name: Package application
      run: |
        cd ./dist/hero-pioneer/osx64/
        zip -r ../hero-pioneer-mac.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hero-pioneer-mac
        path: ./dist/hero-pioneer/hero-pioneer-mac.zip
        retention-days: 5