name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install with exact NW.js version
      run: |
        npm install nw@0.77.0 --save-dev
        npm install
        
    - name: Build with version check
      run: |
        npx nwbuild -v --nwVersion=0.77.0 -p osx64 -o ./dist .
        
    - name: Verify build
      run: |
        if [ -d "./dist" ]; then
          echo "Build successful, contents:"
          find ./dist
        else
          echo "Build failed, dumping debug info:"
          npm ls nw
          npx nwbuild --version
          exit 1
        fi
        
    - name: Package DMG
      if: success()
      run: |
        cd ./dist/*/osx64/
        hdiutil create -volname "MyApp" -srcfolder "MyApp.app" -ov -format UDZO "MyApp.dmg"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-App
        path: ./dist/*/osx64/*.dmg