name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # 使用 Node.js 18 更稳定
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install nw@0.77.0 nw-builder@3.6.0 --save-dev
        npm install
        
    - name: Build application
      run: |
        npx nwbuild \
          --nwVersion=0.77.0 \
          --flavor=normal \
          --platform=osx64 \
          --downloadUrl=https://npmmirror.com/mirrors/nwjs/ \
          -o ./dist \
          .
          
    - name: Verify build output
      run: |
        if [ -d "./dist/hero-pioneer/osx64" ]; then
          echo "Build successful!"
          ls -la ./dist/hero-pioneer/osx64/
        else
          echo "Build failed. Directory contents:"
          ls -la ./dist || echo "No dist directory"
          exit 1
        fi
        
    - name: Create ZIP package
      run: |
        cd ./dist/hero-pioneer/osx64/
        zip -r ../hero-pioneer-mac.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hero-pioneer-mac
        path: ./dist/hero-pioneer/hero-pioneer-mac.zip