name: Build NW.js App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'mybrowser1'  # 关键设置

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./mybrowser1
        run: |
          npm install
          chmod +x node_modules/.bin/*  # 修复所有bin文件权限

      - name: Build macOS app
        working-directory: ./mybrowser1
        run: |
          npx nwbuild --platform mac --outDir ./dist .
          echo "构建结果："
          ls -lR ./dist/  # 构建后立即查看输出

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: ./mybrowser1/dist/*/mac/*.app  # 更通用的匹配