name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci || npm install
        
    - name: Verify environment
      run: |
        echo "Node version: $(node -v)"
        echo "npm version: $(npm -v)"
        npx nwbuild --version
        
    - name: Build macOS application
      run: |
        npx nwbuild -p osx64 -o ./dist ./
        
    - name: Verify build output
      run: |
        echo "Build output structure:"
        find ./dist -type d || true
        ls -la ./dist || true
        
    - name: Create DMG package
      run: |
        BUILD_DIR="./dist/HeroPioneer/osx64"
        if [ -d "$BUILD_DIR" ]; then
          cd "$BUILD_DIR"
          hdiutil create -volname "HeroPioneer" -srcfolder "HeroPioneer.app" -ov -format UDZO "HeroPioneer.dmg"
          echo "DMG created successfully"
        else
          echo "Error: Build directory not found at $BUILD_DIR"
          echo "Actual dist contents:"
          ls -R ./dist || true
          exit 1
        fi
        
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: HeroPioneer-macOS
        path: ./dist/HeroPioneer/osx64/HeroPioneer.dmg
        retention-days: 5