name: Build NW.js for macOS

on:
  push:
    branches: [ main ]  # 只在 main 分支推送时触发
  pull_request:
    branches: [ main ]  # 或 PR 时触发

jobs:
  build-mac:
    runs-on: macos-latest  # 必须使用 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 推荐 Node.js 18/20

      - name: Install dependencies
        run: npm install

      - name: Install NW.js and nw-builder
        run: |
          npm install nw@latest --save-dev
          npm install nw-builder@latest --save-dev

        - name: Debug project structure
          run: |
            echo "当前工作目录: $(pwd)"
            echo "目录结构:"
            ls -R
            echo "package.json 内容:"
            cat package.json || echo "未找到 package.json"
            echo "nw-builder 版本:"
            npx nwbuild --version
    
        - name: Build macOS app
          run: |
            npx nwbuild \
              --platform mac \
              --outDir /Users/runner/work/mybrowser1/mybrowser1/dist \
              /Users/runner/work/mybrowser1/mybrowser1

      - name: Upload macOS app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: ./dist/**/*.app
          
      - name: Create DMG
        run: |
          brew install create-dmg
          cd ./dist/侠客先锋/mac/
          create-dmg YourApp.app
          
      - name: Debug directory
        run: |
          echo "Current path: $(pwd)"
          ls -la