name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Mac NW.js SDK
        run: |
          NW_VERSION="0.77.0"
          curl -L "https://dl.nwjs.io/v${NW_VERSION}/nwjs-sdk-v${NW_VERSION}-osx-x64.zip" -o nwjs-mac.zip
          unzip nwjs-mac.zip -d nwjs-mac
          mv nwjs-mac/nwjs-sdk-v${NW_VERSION}-osx-x64/nwjs.app ./

      - name: Package macOS App
        run: |
          # 创建应用结构
          mkdir -p MyApp.app/Contents/{MacOS,Resources}
          
          # 复制核心文件
          cp -r nwjs.app/Contents/MacOS/* MyApp.app/Contents/MacOS/
          cp nwjs.app/Contents/Info.plist MyApp.app/Contents/
          
          # 安全复制资源
          mkdir -p MyApp.app/Contents/Resources/app.nw
          for item in assets locales weidaan915 index.html package.json; do
            [ -e "$item" ] && cp -r "$item" MyApp.app/Contents/Resources/app.nw/ || echo "跳过 $item"
          done
          
          # 验证结构
          ls -lR MyApp.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-macOS
          path: MyApp.app