name: Build macOS App

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
        npm install nw-builder --save-dev
        
    - name: Build with verbose logging
      run: |
        npx nwbuild -v -p osx64 -o ./dist .
        ls -la ./dist || echo "Build failed"
        
    - name: Check build output
      run: |
        if [ ! -d "./dist" ]; then
          echo "Build failed, dumping debug info:"
          npm ls
          npx nwbuild --version
          exit 1
        fi
        
        APP_PATH=$(find ./dist -name "*.app" -type d | head -n1)
        if [ -z "$APP_PATH" ]; then
          echo "No .app bundle found in dist directory:"
          find ./dist
          exit 1
        fi
        
        mkdir -p ./dist/package/osx64
        cp -r "$APP_PATH" ./dist/package/osx64/
        
    - name: Create DMG
      run: |
        cd ./dist/package/osx64
        APP_NAME=$(basename *.app .app)
        hdiutil create -volname "$APP_NAME" -srcfolder "$APP_NAME.app" -ov -format UDZO "$APP_NAME.dmg"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-App
        path: ./dist/package/osx64/*.dmg