name: 构建 macOS 应用

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: 安装依赖
      run: |
        npm install
        npm ls
        
    - name: 调试信息
      run: |
        echo "NW.js版本:"
        nw --version || echo "NW.js未全局安装"
        echo "当前目录内容:"
        ls -la
        
    - name: 构建应用
      run: |
        npx nwbuild -v -p osx64 -o ./dist ./
        echo "构建后目录内容:"
        ls -la ./dist || echo "dist目录不存在"
        
    - name: 检查构建输出
      run: |
        if [ -d "./dist" ]; then
          echo "找到dist目录，内容如下:"
          find ./dist -type d
          
          # 尝试自动查找应用目录
          APP_PATH=$(find ./dist -name "*.app" -type d | head -n 1)
          if [ -n "$APP_PATH" ]; then
            echo "找到应用包: $APP_PATH"
            mkdir -p ./dist/package/osx64
            cp -r "$APP_PATH" ./dist/package/osx64/
          else
            echo "错误: 未找到.app应用包"
            exit 1
          fi
        else
          echo "错误: dist目录未生成"
          exit 1
        fi
        
    - name: 创建DMG安装包
      run: |
        cd ./dist/package/osx64
        APP_NAME=$(basename *.app .app)
        hdiutil create -volname "$APP_NAME" -srcfolder "$APP_NAME.app" -ov -format UDZO "$APP_NAME.dmg"
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 应用安装包-macOS
        path: ./dist/package/osx64/*.dmg